# Generated by Django 3.0.14 on 2023-04-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passwordagain',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
